class Fruit:
    sweet_gem_berry = "Sweet Gem Berry"
    any = "Any Fruit"
    blueberry = "Blueberry"
    melon = "Melon"
    apple = "Apple"
    apricot = "Apricot"
    cherry = "Cherry"
    orange = "Orange"
    peach = "Peach"
    pomegranate = "Pomegranate"
    banana = "Banana"
    mango = "Mango"
    pineapple = "Pineapple"
    ancient_fruit = "Ancient Fruit"
    strawberry = "Strawberry"
    starfruit = "Starfruit"
    rhubarb = "Rhubarb"
    grape = "Grape"
    cranberries = "Cranberries"
    hot_pepper = "Hot Pepper"
    powdermelon = "Powdermelon"
    qi_fruit = "Qi Fruit"


class Vegetable:
    any = "Any Vegetable"
    parsnip = "Parsnip"
    garlic = "Garlic"
    bok_choy = "Bok Choy"
    wheat = "Wheat"
    potato = "Potato"
    corn = "Corn"
    tomato = "Tomato"
    pumpkin = "Pumpkin"
    unmilled_rice = "Unmilled Rice"
    beet = "Beet"
    hops = "Hops"
    cauliflower = "Cauliflower"
    amaranth = "Amaranth"
    kale = "Kale"
    artichoke = "Artichoke"
    tea_leaves = "Tea Leaves"
    eggplant = "Eggplant"
    green_bean = "Green Bean"
    red_cabbage = "Red Cabbage"
    yam = "Yam"
    radish = "Radish"
    taro_root = "Taro Root"
    carrot = "Carrot"
    summer_squash = "Summer Squash"
    broccoli = "Broccoli"


class SVEFruit:
    slime_berry = "Slime Berry"
    monster_fruit = "Monster Fruit"
    salal_berry = "Salal Berry"


class SVEVegetable:
    monster_mushroom = "Monster Mushroom"
    void_root = "Void Root"
    ancient_fiber = "Ancient Fiber"


class DistantLandsCrop:
    void_mint = "Void Mint Leaves"
    vile_ancient_fruit = "Vile Ancient Fruit"



class CornFruit:
    bell_peppr = "Bell Pepper"
    kiwi = "Kiwifruit"
    watermelon = "Watermelon"
    avocado = "Avocado"
    pear = "Pear"
    raspberry = "Raspberry"

class CornVegetable:
    basil = "Basil"
    cucumber = "Cucumber"
    lettuce = "Lettuce"
    onion = "Onion"
    peanut = "Peanut"
    spinach = "Spinach"
    sugarcane = "Sugarcane"
    turnip = "Turnip"
    zucchini = "Zucchini"
    olive = "Olive"
    peppercorn = "Peppercorn"

class CornCropExtFruit:
    canary_melon = "Canary Melon"
    cantaloupe = "Cantaloupe"
    groundcherry = "Groundcherries"
    habanero = "Habanero"
    honeydew = "Honeydew"
    jalapeno = "Jalapeno"
    passion_fruit = "Passion Fruit"
    currant = "Black Currants"
    elderberry = "Elderberries"
    gooseberry = "Gooseberry"
    juniper = "Juniper Berries"
    white_grape = "White Grape"
    sapodilla = "Sapodilla"

class CornCropExtVegetable:
    adzuki = "Adzuki Bean"
    agave = "Agave"
    asparagus = "Asparagus"
    bamboo = "Bamboo"
    barley = "Barley"
    black_bean = "Black Beans"
    blue_agave = "Blue Agave"
    buckwheat = "Buckwheat"
    butternut_squash = "Butternut Squash"
    cabbage = "Cabbage"
    cassava = "Cassava"
    celery = "Celery"
    chickpea = "Chickpea"
    daikon = "Daikon"
    durum = "Durum"
    ginseng = "Ginseng"
    green_pea = "Green Peas"
    kidney_bean = "Kidney Beans"
    navy_bean = "Navy Beans"
    oat = "Oats"
    okra = "Okra"
    pinto_bean = "Pinto Beans"
    quinoa = "Quinoa"
    red_onion = "Red Onion"
    shallot = "Shallot"
    sugar_beet = "Sugar Beet"
    sweet_potato = "Sweet Potato"
    wasabi = "Wasabi Root"


class CornHerbExtVegetable:
    aloe = "Aloe"
    catnip = "Catnip"
    chives = "Chives"
    cilantro = "Cilantro"
    dill = "Dill"
    fennel = "Fennel"
    fenugreek = "Fenugreek"
    lemongrass = "Lemongrass"
    licorice_root = "Licorice Root"
    marjoram = "Marjoram"
    mint = "Mint"
    oregano = "Oregano"
    parsley = "Parsley"
    perilla = "Perilla Leaves"
    rosemary = "Rosemary"
    sage = "Sage"
    tarragon = "Tarragon"
    thyme = "Thyme"
    wormwood = "Wormwood"
    bay = "Bay Leaves"
    camphor = "Camphor Leaves"
    eucalyptus = "Eucalyptus Leaves"
    melaleuca = "Melaleuca Leaves"

class CornTreeExtFruit:
    breadfruit = "Breadfruit"
    dragon_fruit = "Dragon Fruit"
    durian = "Durian"
    fig = "Fig"
    grapefruit = "Grapefruit"
    lemon = "Lemon"
    lime = "Lime"
    lychee = "Lychee"
    nectarine = "Nectarine"
    papaya = "Papaya"
    persimmon = "Persimmon"
    plantain = "Plantain"
    pomelo = "Pomelo"
    ume = "Ume"
    yuzu = "Yuzu"
