class Seed:
    amaranth = "Amaranth Seeds"
    artichoke = "Artichoke Seeds"
    bean = "Bean Starter"
    beet = "Beet Seeds"
    blueberry = "Blueberry Seeds"
    bok_choy = "Bok Choy Seeds"
    broccoli = "Broccoli Seeds"
    cactus = "Cactus Seeds"
    carrot = "Carrot Seeds"
    cauliflower = "Cauliflower Seeds"
    coffee_starter = "Coffee Bean (Starter)"
    """This item does not really exist and should never end up being displayed. 
    It's there to patch the loop in logic because "Coffee Bean" is both the seed and the crop."""
    coffee = "Coffee Bean"
    corn = "Corn Seeds"
    cranberry = "Cranberry Seeds"
    eggplant = "Eggplant Seeds"
    fairy = "Fairy Seeds"
    garlic = "Garlic Seeds"
    grape = "Grape Starter"
    hops = "Hops Starter"
    jazz = "Jazz Seeds"
    kale = "Kale Seeds"
    melon = "Melon Seeds"
    mixed = "Mixed Seeds"
    mixed_flower = "Mixed Flower Seeds"
    parsnip = "Parsnip Seeds"
    pepper = "Pepper Seeds"
    pineapple = "Pineapple Seeds"
    poppy = "Poppy Seeds"
    potato = "Potato Seeds"
    powdermelon = "Powdermelon Seeds"
    pumpkin = "Pumpkin Seeds"
    qi_bean = "Qi Bean"
    radish = "Radish Seeds"
    rare_seed = "Rare Seed"
    red_cabbage = "Red Cabbage Seeds"
    rhubarb = "Rhubarb Seeds"
    rice = "Rice Shoot"
    spangle = "Spangle Seeds"
    starfruit = "Starfruit Seeds"
    strawberry = "Strawberry Seeds"
    summer_squash = "Summer Squash Seeds"
    sunflower = "Sunflower Seeds"
    taro = "Taro Tuber"
    tomato = "Tomato Seeds"
    tulip = "Tulip Bulb"
    wheat = "Wheat Seeds"
    yam = "Yam Seeds"


class TreeSeed:
    acorn = "Acorn"
    maple = "Maple Seed"
    mossy = "Mossy Seed"
    mystic = "Mystic Tree Seed"
    pine = "Pine Cone"
    mahogany = "Mahogany Seed"
    mushroom = "Mushroom Tree Seed"


class SVESeed:
    stalk = "Stalk Seed"
    fungus = "Fungus Seed"
    slime = "Slime Seed"
    void = "Void Seed"
    shrub = "Shrub Seed"
    ancient_fern = "Ancient Fern Seed"


class DistantLandsSeed:
    void_mint = "Void Mint Seeds"
    vile_ancient_fruit = "Vile Ancient Fruit Seeds"


class CornSeed:
    basil = "Basil Seeds"
    bell_pepper = "Bell Pepper Seeds"
    turnip = "Turnip Seeds"
    cotton = "Cotton Seeds"
    cucumber = "Cucumber Starter"
    kiwi = "Kiwifruit Seeds"
    lettuce = "Lettuce Seeds"
    onion = "Onion Seeds"
    peanut = "Peanut Seeds"
    spinach = "Spinach Seeds"
    soybean = "Soybean" 
    soybean_starter = "Soybean Seeds (Starter)"
    sugarcane = "Sugarcane Shoot"
    watermelon = "Watermelon Seeds"
    zucchini = "Zucchini Seeds"



class CornCropExtSeed:
    adzuki = "Adzuki Bean Seeds"
    agave = "Agave Seeds"
    asparagus = "Asparagus Seeds"
    bamboo = "Bamboo Shoot"
    barley = "Barley Seeds"
    black_bean = "Black Bean Starter"
    blue_agave = "Blue Agave Seeds"
    buckwheat = "Buckwheat Seeds"
    butternut_squash = "Butternut Squash Seeds"
    cabbage = "Cabbage Seeds"
    canary_melon = "Canary Melon Seeds"
    canola = "Canola Seeds"
    cantaloupe = "Cantaloupe Seeds"
    cassava = "Cassava Seeds"
    celery = "Celery Seeds"
    chickpea = "Chickpea Seeds"
    daikon = "Daikon Seeds"
    durum = "Durum Seeds"
    ginseng = "Ginseng Seeds"
    green_pea = "Green Pea Strater"
    groundcherry = "Groundcherry Seeds"
    habanero = "Habanero Seeds"
    honeydew = "Honeydew Seeds"
    jalapeno = "Jalapeno Seeds"
    kidney_bean = "Kidney Bean Starter"
    navy_bean = "Navy Bean Starter"
    oat = "Oat Seeds"
    okra = "Okra Seeds"
    passion_fruit = "Passion Fruit Starter"
    pinto = "Pinto Bean Starter"
    quinoa = "Quinoa Seeds"
    red_onion = "Red Ontion Seeds"
    shallot = "Shallot Seeds"
    sugar_beet = "Sugar Beet Seeds"
    sweet_potato = "Sweet Potato Seeds"
    wasabi = "Wasabi Tuber"


class CornHerbExtSeed:
    aloe = "Aloe Pod"
    catnip = "Catnip Seeds"
    chive = "Chive Seeds"
    cilantro = "Coriander Seeds"
    cumin = "Cumin Seeds"
    cumin_starter = "Cumin Seeds (Starter)"
    dill = "Dill Seeds"
    fennel = "Fennel Seeds"
    fenugreek = "Fenugreek Seeds"
    lemongrass = "Lemongrass Seeds"
    licorice_root = "Licorice Seeds"
    marjoram = "Majoram Seeds"
    mint = "Mint Seeds"
    oregano = "Oregano Seeds"
    parsley = "Parsley Seeds"
    perilla = "Perilla Seeds"
    rosemary = "Rosemary Seeds"
    sage = "Sage Seeds"
    tarragon = "Tarragon Seeds"
    thyme = "Thyme Seeds"
    turmeric = "Turmeric Seeds"
    wormwood = "Wormwood Seeds"


